name: exercises-preview

on: 
  pull_request:

jobs:
  exercises-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup RUST Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install mdBook
        run: cargo install mdbook
      - name: Build
        working-directory: exercises
        run: mdbook build
      - name: Deploy Exercises Preview 🚀
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: target/book/
          umbrella-dir: exercises/pr-preview
