name: slides-preview

on: 
  pull_request:

jobs:
  slides-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install
        working-directory: slides
        run: yarn
      - name: Build Course Information
        working-directory: slides
        run: npx slidev build --out dist/0 --base slides/pr-preview/pr-${{ github.event.number }}/0 0-intro.md
      - name: Build Module A1
        working-directory: slides
        run: npx slidev build --out dist/A1 --base slides/pr-preview/pr-${{ github.event.number }}/A1 A1-intro-to-rust.md
      - name: Build Module A2 Tools
        working-directory: slides
        run: npx slidev build --out dist/A2-tools --base slides/pr-preview/pr-${{ github.event.number }}/A2-tools A2-tools.md
      - name: Build Module A2
        working-directory: slides
        run: npx slidev build --out dist/A2 --base slides/pr-preview/pr-${{ github.event.number }}/A2 A2-advanced-intro.md
      - name: Build Module A3
        working-directory: slides
        run: npx slidev build --out dist/A3 --base slides/pr-preview/pr-${{ github.event.number }}/A3 A3-traits-generics.md
      - name: Build Module B
        working-directory: slides
        run: npx slidev build --out dist/B --base slides/pr-preview/pr-${{ github.event.number }}/B B-application-programming.md
      - name: Build Module C
        working-directory: slides
        run: npx slidev build --out dist/C --base slides/pr-preview/pr-${{ github.event.number }}/C C-concurrency-parallelism.m
      - name: Build Module D
        working-directory: slides
        run: npx slidev build --out dist/D --base slides/pr-preview/pr-${{ github.event.number }}/D D-trait-objects-patterns.md
      - name: Build Module E
        working-directory: slides
        run: npx slidev build --out dist/E --base slides/pr-preview/pr-${{ github.event.number }}/E E-async-web.md
      - name: Build Module F
        working-directory: slides
        run: npx slidev build --out dist/F --base slides/pr-preview/pr-${{ github.event.number }}/F F-safe-unsafe-rust.md
      - name: Build Module G
        working-directory: slides
        run: npx slidev build --out dist/G --base slides/pr-preview/pr-${{ github.event.number }}/G G-ffi.md
